version: 1
formatters:
  simple:
    format: '%(levelname)-8s (%(asctime)s): %(message)s (Line: %(lineno)d) [%(filename)s]'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/logs.log
    maxBytes: 1048576  # 1 MB
    backupCount: 3  # Хранить до 3 архивных логов
    encoding: utf8


loggers:
  my_logger:
    level: DEBUG
    handlers: [file]
    propagate: no

root:
  level: DEBUG
  handlers: [file]
