name: Manual Deploy

on:
  workflow_dispatch:  # Запуск вручную через интерфейс GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}          # Например, "192.168.1.100"
          username: ${{ secrets.SSH_USER }}      # Например, "ubuntu"
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}            # Приватный SSH-ключ из секретов
          port: 8022

          # Указываем команды для деплоя
          script: |
            # Переход в директорию проекта
            cd /home/srv_adm/python/
            # Обновление репозитория
            git pull origin main
            # Активация виртуального окружения
            source /home/srv_adm/python/venv/bot_venv/bin/activate
            # Переход в директорию проекта
            cd /home/srv_adm/python/FishBot/
            # Установка зависимостей (если нужно)
            pip install -r requirements.txt
            # Перезапуск сервиса
            sudo systemctl restart bot
